version: 2.1

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-1604:202007-01
      # DO NOT USE THIS YET! This costs 200 credits *per job run* so is extremely expensive for the free plan, but we can turn it on one day if we get more credits
      # docker_layer_caching: true

jobs:
  build:
    executor: ubuntu_vm
    steps:
      - checkout
      - run: "echo << pipeline.git.base_revision >>"

      # TODO Add caching like in https://circleci.com/docs/2.0/language-go/
      
      - run: "bash .circleci/check_for_changelog_in_diff.sh << pipeline.git.base_revision >> ${CIRCLE_BRANCH}"
      - run: scripts/build.sh
  push_docker_image:
    executor: ubuntu_vm
    steps:
      - run: "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
      # TODO change the image name to be parameterized - it's hardcoded right now
      - run: "docker push kurtosistech/kurtosis-go-example:<< pipeline.git.branch >>"

workflows:
  main:
    # We only want to run the workflow when we have a pull request!
    when: "<< pipeline.git.base_revision >>"
    jobs:
      - build
      - push_docker_image:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
