version: 2.1

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-1604:202007-01
      # DO NOT USE THIS YET! This costs 200 credits *per job run* so is extremely expensive for the free plan, but we can turn it on one day if we get more credits
      # docker_layer_caching: true

jobs:
  check_for_changelog:
    executor: ubuntu_vm
    steps:
      - run: "bash .circleci/check_for_changelog_in_diff.sh << pipeline.git.base_revision >> ${CIRCLE_BRANCH}"
  build:
    executor: ubuntu_vm
    steps:
      - checkout

      # TODO Add caching like in https://circleci.com/docs/2.0/language-go/
      
      - run: scripts/build.sh
  push_docker_image:
    executor: ubuntu_vm
    steps:
      - run: "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
      # TODO change the image name to be parameterized - it's hardcoded right now
      - run: "docker push kurtosistech/kurtosis-go-example:<< pipeline.git.branch >>"

workflows:
  pr_validation:
    when: "$CIRCLE_PULL_REQUEST"
    jobs:
      - check_for_changelog
      - build:
          requires:
            - check_for_changelog

  push_stable_images:
    when:
      or:
        - equal: [ "develop", "<< pipeline.git.branch >>" ]
        - equal: [ "master", "<< pipeline.git.branch >>" ]
    jobs:
      - build
      - push_docker_image:
          requires:
            - build
